Modularize controllers routers
jktyy-whereabouts-v2/whereabouts-v2 pull request #10
Opened 2023-04-25 02:56 UTC by jennyschmalz

## Overview

**Issue Type**

- [x] Bug
- [ ] Feature
- [x] Tech Debt

**Description**

1. Modularize controllers
2. Modularize routers
3. Fix database queries
4. Test routes with Postman (backend)

2023-04-25 03:43 UTC, YouruiR approved these changes

2023-04-25 03:46 UTC, YouruiR reviewed
Please pull from dev, merge your branch with dev, and fix the merge conflicts

2023-04-25 03:47 UTC, YouruiR requested changes
Please pull from dev, merge your branch with dev, and fix the merge conflicts

2023-04-26 00:38 UTC, YouruiR approved these changes

2023-04-26 00:46 UTC, wendyys96 approved these changes

2023-04-26 00:46 UTC, merged